version: "3.9"

name: "clean-architecture-csharp"

services:
  sql:
    image: docker.io/postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres  

volumes:
  pgdata:
