name: Code check

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Tool restore
        run: cd src && dotnet tool restore
      - name: Test
        run: cd src && dotnet test ./UnitTests     
      - name: Csharpier check
        run: |
          cd src
          dotnet tool restore
          dotnet csharpier --check .        
